-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-05-28 15:35:24 BRT
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE labor_force CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE project_stages CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE budgets CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE projects CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE managers CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE customers CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE budgets 
    ( 
     budget_id               NUMBER GENERATED BY DEFAULT AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     project_id              NUMBER  NOT NULL , 
     manager_id              NUMBER  NOT NULL , 
     estimated_material_cost NUMBER (12,2)  NOT NULL , 
     estimated_labor_cost    NUMBER (12,2)  NOT NULL , 
     base_profit_margin      NUMBER (12,2)  NOT NULL , 
     additional_margin       NUMBER (12,2) DEFAULT 0.00  NOT NULL , 
     total_value             NUMBER (12,2) AS ( estimated_material_cost + estimated_labor_cost + base_profit_margin + additional_margin ) VIRTUAL 
    ) 
    LOGGING 
;

ALTER TABLE budgets 
    ADD CONSTRAINT pk_budgets PRIMARY KEY ( budget_id ) ;

ALTER TABLE budgets 
    ADD CONSTRAINT uq_budget_project UNIQUE ( project_id ) ;

CREATE TABLE customers 
    ( 
     customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     first_name  VARCHAR2 (50)  NOT NULL , 
     last_name   VARCHAR2 (50)  NOT NULL , 
     email       VARCHAR2 (100) , 
     phone       VARCHAR2 (20) 
    ) 
    LOGGING 
;

ALTER TABLE customers 
    ADD CONSTRAINT pk_customers PRIMARY KEY ( customer_id ) ;

ALTER TABLE customers 
    ADD CONSTRAINT uq_customers_email UNIQUE ( email ) ;

CREATE TABLE labor_force 
    ( 
     labor_id    NUMBER GENERATED BY DEFAULT AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     project_id  NUMBER  NOT NULL , 
     worker_name VARCHAR2 (100)  NOT NULL , 
     specialty   VARCHAR2 (50)  NOT NULL , 
     daily_rate  NUMBER (10,2)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE labor_force 
    ADD CONSTRAINT pk_labor_force PRIMARY KEY ( labor_id ) ;

CREATE TABLE managers 
    ( 
     manager_id NUMBER GENERATED BY DEFAULT AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     first_name VARCHAR2 (50)  NOT NULL , 
     last_name  VARCHAR2 (50)  NOT NULL , 
     role       VARCHAR2 (50)  NOT NULL , 
     email      VARCHAR2 (100) , 
     phone      VARCHAR2 (20) 
    ) 
    LOGGING 
;

ALTER TABLE managers 
    ADD CONSTRAINT pk_staff PRIMARY KEY ( manager_id ) ;

ALTER TABLE managers 
    ADD CONSTRAINT uq_managers_email UNIQUE ( email ) ;

CREATE TABLE project_stages 
    ( 
     stage_id   NUMBER GENERATED BY DEFAULT AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     project_id NUMBER  NOT NULL , 
     stage_name VARCHAR2 (100)  NOT NULL , 
     start_date DATE  NOT NULL , 
     end_date   DATE , 
     status     VARCHAR2 (30) DEFAULT 'Not Started'  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE project_stages 
    ADD CONSTRAINT chk_stage_dates 
    CHECK (end_date >= start_date)
;
ALTER TABLE project_stages 
    ADD CONSTRAINT pk_project_stages PRIMARY KEY ( stage_id ) ;

CREATE TABLE projects 
    ( 
     project_id         NUMBER GENERATED BY DEFAULT AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     customer_id        NUMBER  NOT NULL , 
     manager_id         NUMBER  NOT NULL , 
     project_name       VARCHAR2 (100)  NOT NULL , 
     location           VARCHAR2 (255)  NOT NULL , 
     start_date         DATE  NOT NULL , 
     estimated_end_date DATE  NOT NULL , 
     status             VARCHAR2 (30) DEFAULT 'Planning'  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE projects 
    ADD CONSTRAINT chk_project_dates 
    CHECK (estimated_end_date >= start_date)
;
ALTER TABLE projects 
    ADD CONSTRAINT pk_projects PRIMARY KEY ( project_id ) ;

ALTER TABLE budgets 
    ADD CONSTRAINT fk_budgets_projects FOREIGN KEY 
    ( 
     project_id
    ) 
    REFERENCES projects 
    ( 
     project_id
    ) 
    ON DELETE CASCADE 
    NOT DEFERRABLE 
;

ALTER TABLE budgets 
    ADD CONSTRAINT fk_budgets_staff FOREIGN KEY 
    ( 
     manager_id
    ) 
    REFERENCES managers 
    ( 
     manager_id
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE labor_force 
    ADD CONSTRAINT fk_labor_force_projects FOREIGN KEY 
    ( 
     project_id
    ) 
    REFERENCES projects 
    ( 
     project_id
    ) 
    ON DELETE CASCADE 
    NOT DEFERRABLE 
;

ALTER TABLE projects 
    ADD CONSTRAINT fk_projects_customers FOREIGN KEY 
    ( 
     customer_id
    ) 
    REFERENCES customers 
    ( 
     customer_id
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE projects 
    ADD CONSTRAINT fk_projects_staff FOREIGN KEY 
    ( 
     manager_id
    ) 
    REFERENCES managers 
    ( 
     manager_id
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE project_stages 
    ADD CONSTRAINT fk_stages_projects FOREIGN KEY 
    ( 
     project_id
    ) 
    REFERENCES projects 
    ( 
     project_id
    ) 
    ON DELETE CASCADE 
    NOT DEFERRABLE 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             17
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
