CREATE TABLE invoices 
    ( 
     invoice_id      NUMBER GENERATED BY DEFAULT AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     project_id      NUMBER  NOT NULL , 
     invoice_number  VARCHAR2 (50)  NOT NULL , 
     issue_date      DATE  NOT NULL , 
     due_date        DATE  NOT NULL , 
     invoice_amount  NUMBER (12,2)  NOT NULL , 
     status          VARCHAR2 (30) DEFAULT 'Issued' NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE invoices 
    ADD CONSTRAINT pk_invoices PRIMARY KEY ( invoice_id ) ;

ALTER TABLE invoices 
    ADD CONSTRAINT uq_invoice_number UNIQUE ( invoice_number ) ;

CREATE TABLE payments_received 
    ( 
     payment_id      NUMBER GENERATED BY DEFAULT AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     invoice_id      NUMBER  NOT NULL ,         -- Vinculado direto à nota emitida
     payment_date    DATE  NOT NULL ,           -- Quando o dinheiro caiu na conta
     amount_received NUMBER (12,2)  NOT NULL ,  -- Valor pago (pode ser parcial)
     payment_method  VARCHAR2 (50)  NOT NULL    -- Pix, Transferência, Boleto
    ) 
    LOGGING 
;

ALTER TABLE payments_received 
    ADD CONSTRAINT pk_payments_received PRIMARY KEY ( payment_id ) ;

CREATE TABLE operational_expenses 
    ( 
     expense_id      NUMBER GENERATED BY DEFAULT AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     project_id      NUMBER  NOT NULL ,         -- A qual obra esse custo pertence
     expense_type    VARCHAR2 (50)  NOT NULL ,  -- Material, Taxa, Equipamento, Terceirizados
     description     VARCHAR2 (255)  NOT NULL , -- Ex: "Compra de 50 sacos de cimento"
     expense_date    DATE  NOT NULL ,           -- Data do pagamento/desembolso
     expense_amount  NUMBER (12,2)  NOT NULL   -- Quanto custou
    ) 
    LOGGING 
;

ALTER TABLE operational_expenses 
    ADD CONSTRAINT pk_operational_expenses PRIMARY KEY ( expense_id ) ;

