CREATE TABLE invoices 
    ( 
     invoice_id      NUMBER GENERATED BY DEFAULT AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     project_id      NUMBER  NOT NULL , 
     invoice_number  VARCHAR2 (50)  NOT NULL , 
     issue_date      DATE  NOT NULL , 
     due_date        DATE  NOT NULL , 
     invoice_amount  NUMBER (12,2)  NOT NULL , 
     status          VARCHAR2 (30) DEFAULT 'Issued' NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE invoices 
    ADD CONSTRAINT pk_invoices PRIMARY KEY ( invoice_id ) ;

ALTER TABLE invoices 
    ADD CONSTRAINT uq_invoice_number UNIQUE ( invoice_number ) ;
